### ISSUE TITLE
[finops resources] Website Contribution for the Reducing Waste Project

### ISSUE THREAD

**Issue by stevetrask** [finopsfoundation/framework#577]
Hi,

I suggest to add unattached NICs and others for Azure. I will give this as an example to start with.
It would provide a minor to none cost saving, but more seen as "keeping it nice and tidy", no waste vision.  
Source: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/find-unattached-nics

It would be great to be able to contribute more, how can I get engage and possible update directly on the page itself some day. 
I work within IKEA in our Cloud Center of Excellence team and we do work a lot with Cost optimization currently.

Br,
Joakim

Submitted on: https://www.finops.org/projects/reducing-waste/

**Comment by stevetrask** [comment]
@vnm-fodo can you review this submission?

**Comment by vnm-fodo** [comment]
hey @stevetrask  - let's get Joakim  to provide a write-up for it - ideally from his experience/perspective.

as he stated - does not move the needle on cloud cost savings - but for the sake of completeness - it fits nicely within the Reducing Waste project since the project focuses on providing info to help identify types of cloud waste by service provider.

lmk if you want /me to reply to him.

**Comment by andrewnhem** [comment]
Resolved via #715
